- hosts: localhost
  tasks:
  - name: Show all vars
    setup:
    register: result
  - name: Ansible create file with content example
    copy:
      dest: "/tmp/list_vars"
      content: |
        "{{result}}"
