- hosts: localhost
  tasks:
  - name: Show all vars
    setup:
    register: result
  - name: Ansible create file with content example
    copy:
      dest: "~/list_vars"
      content: |
        "{{result}}"

  - name: Print
    debug: var=result
    
  - name: Get IP
    shell: hostname -I
    register: ip
  - debug: var=ip
