- hosts: localhost
  gather_facts: false
  vars:
    state:
    reboot:
  tasks:
  - name: set selinux
    selinux:
      policy: targeted
      state: "{{ state }}"
  - name: check if reboot needed
    shell: reboot
    when: reboot == "Yes"
