- hosts: localhost
  gather_facts: false
  vars:
    state:
    port_start:
    port_end:
    protocol:
  tasks:
  - name: set firewall
    firewalld:
      state: "{{ state }}"
      port: "{{ port_start }}-{{ port_end }}/{{ protocol }}"
      permanent: true
      immediate: true
