---
# tasks file for webserver
- name: Install nginx and firewalld
  yum: name=nginx,firewalld state=installed

- name: Start services
  service: name={{item}} state=started
  with_items:
    - firewalld
    - nginx

- name: Open firewall
  firewalld: state=enabled port=80/tcp permanent=true immediate=true

- name: Add nginx template
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
    mode: u=rw,g=r,o=r
    owner: root
    group: root

- name: Restart nginx
  service: name=nginx state=restarted
