---
# tasks file for loadbalancer
- name: Fail when webservers is not defined
  assert:
    that:
      - webservers is defined

- name: Install haproxy and firewalld
  yum: name=haproxy,firewalld,python-pip state=installed

- name: Start services
  service: name={{item}} state=started
  with_items:
    - firewalld
    - haproxy

- name: Open firewall
  firewalld: state=enabled port=80/tcp permanent=true immediate=true

- name: Add haproxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 660
    owner: root
    group: root

- name: Restart haproxy
  service: name=haproxy state=restarted

- name: Install haproxy stats
  pip:
    name: haproxy-stats
    state: present

- name: Ensure facts dir exists
  file:
    state: directory
    path: /etc/ansible/facts.d
    owner: root
    group: root
    mode: 770

- name: Add custom facts scripts
  copy:
    src: files/loadbalancer.py
    dest: /etc/ansible/facts.d/loadbalancer.py
    mode: 770
    owner: root
    group: root

- name: Reload facts
  setup: "filter=ansible_local"

- name: Print stats
  shell: echo {{ansible_local.loadbalancer}} >> /root/lb_stats
